spring:
  datasource:
    url: jdbc:h2:mem:auction_db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-here-should-be-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.auctionapp: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.jooq: DEBUG

auction:
  bidding:
    min-increment: 1000
  concurrency:
    strategy: optimistic # 기본값은 낙관적 락 사용
  websocket:
    endpoint: /ws
    destination-prefix: /topic
    application-prefix: /app 