spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: auction_user
    password: auction_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mvc:
    static-path-pattern: /** # 정적 리소스 경로 패턴
  web:
    resources:
      static-locations: classpath:/static/ # 정적 리소스 위치 명시적 설정
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  quartz:
      job-store-type: jdbc
      jdbc:
          initialize-schema: always
      properties:
          org.quartz.scheduler.instanceName: AuctionScheduler
          org.quartz.scheduler.instanceId: AUTO
          org.quartz.jobStore.isClustered: true

server:
  port: 8080
  # context-path 제거 - API와 정적 리소스 분리를 위해 제거

jwt:
  secret: eW91ci1zZWNyZXQta2V5LWhlcmUtc2hvdWxkLWJlLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnM=
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.auctionapp: DEBUG
    org.springframework.web: INFO
    org.quartz: DEBUG

auction:
  websocket:
    endpoint: /ws
    destination-prefix: /topic
    application-prefix: /app

app:
  security:
    dev-mode: true
    extended-token-expiry: true  # 개발 환경에서 토큰 유효 기간 연장 (예: 1일)

# Redisson 설정
redisson:
  address: ${REDISSON_ADDRESS:redis://localhost:6379}
