spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: auction_user
    password: auction_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mvc:
    static-path-pattern: /**

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-here-should-be-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.auctionapp: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.jooq: DEBUG

auction:
  bidding:
    min-increment: 1000
  concurrency:
    strategy: optimistic # 기본값은 낙관적 락 사용
  websocket:
    endpoint: /ws
    destination-prefix: /topic
    application-prefix: /app 